[platformio]
default_envs = master, slave-01, slave-02, motor

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_qspi
board_build.partitions = default_8MB.csv

monitor_speed = 2000000
monitor_filters = send_on_enter
monitor_rts = 0
monitor_dtr = 0

[env:master]
build_src_filter =
    -<*>
    +<master/>
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101

[env:slave-01]
board_upload.flash_size = 4MB
board_build.partitions = default.csv
monitor_speed = 115200
build_src_filter =
    -<*>
    +<slave-01/>
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

[env:slave-02]
board_upload.flash_size = 4MB
board_build.partitions = default.csv
monitor_speed = 115200
build_src_filter =
    -<*>
    +<slave-02/>
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

[env:motor]
build_src_filter =
    -<*>
    +<motor/>
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
